---
title: "Your Document Title"
author: "Document Author"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---


```{r, echo=F}
#SKIP TO LINE 992 TO READ IN COMPLETED DATA FILES AND RUN MASTIF

username <- function() 
{ 
readline("Please enter username:  ")
} 
user <- username()
print(paste0("proceeding as ", user))
```


```{r getFiles, eval = T, echo=T}
if(user == "chase"){
  Rcpp::sourceCpp('/Volumes/clark/clark.unix/makeMast/RcppFunctions/cppFns.cpp')
  source('/Volumes/clark/clark.unix/makeMast/RFunctions/mastifFunctions.r')
    } else{
      Rcpp::sourceCpp('/Volumes/clark/clark.unix/makeMast/RcppFunctions/cppFns.cpp')
      source('../RFunctions/mastifFunctions.r')
      }
```


```{r readDF, eval=F, echo=F}

if(user == "chase"){
    path <- "/Volumes/clark/clark.unix/allocationmodel/datafiles/"
    } else{
      path  <- "../dataFiles/"
      }


years       <- 1991:2018

genera <- c('abie','acer','aila','amel','betu','carp',
            'cary','celt','cerc','chio','corn','fagu','frax',
            'ilex','juni','liqu','liri','magn',
            'moru','nyss','ostr','oxyd','pice','pinu','prun',
            'quer','robi','sass','sorb','tili','tsug','ulmu')
genFull <- c('abies','acer','ailanthus','amelanchier','betula','carpinus',
             'carya','celtis','cercis','chionanthus','cornus','fagus','fraxinus',
             'ilex','juniperus','liquidambar','liriodendron','magnolia',
             'morus','nyssa','ostrya','oxydendron','picea','pinus','prunus',
             'quercus','robinia','sassafras','sorbus','tilia','tsuga','ulmus')

omitNames   <- c('acerIMMA','liriTuli_flower','betuUNKN_flower','caryIMMA',
                 'cornIMMA','acerRubr_flower',' betuUNKN_flower',
                 'nyssIMMA','oxydArbo_flower','oxydIMMA','pinuImma_fruit',
                 'piceRubeIMMA','querIMMA','tiliAmer_flower')
changeNames <- rbind( cbind('ulmuUNKN','ulmuAlat'),
                      cbind('acerUNKN','acerRubr'),
                      cbind('acerrubr','acerRubr'))
colnames(changeNames) <- c('from','to')

```


This builds compressed files:

```{r}

#genusName   <- 'abie'

treeID      <- 'ID'
yrCols      <- c('diam','canopy')
treeStart   <- 'censinyr'
treeEnd     <- c('deathyr','censoryr')
x           <- 'x'
y           <- 'y'

trapCols <- c("plot","trapID","trap","x","y","UTMx","UTMy","elev")

trapID <- 'trapnum'

#path <- "/nas/clark/clark.unix/allocationmodel/datafiles/"


plots <- c('CW_118', 'CW_218', 'CW_318', 'CW_427', 'CW_527', 'CW_LG','CW_UG',
           'MH_F','MH_P','DF_HW', 'DF_EW', 'DF_BW','DF_EE',
           'GSNP_PK', 'GSNP_CD', 'GSNP_ND','HF_S', 'HF_BW')

#plots    <- list.files(paste0(path, 'trees/', sep=''))
#treeFile <- plots[ grep('active',plots) ]
#locFile  <- plots[ grep('UTM',plots) ]

sfiles    <- list.files(paste0(path, 'seeds/', sep=''))
seedFile <- sfiles[ grep('active',sfiles) ]
locFile  <- sfiles[ grep('UTM',sfiles) ]

plots <- unlist( strsplit(plots, "_active.txt") )

seedFile <- paste0(path, 'seeds/', plots, '_active.txt', sep='')
locFile  <- paste0(path, 'seeds/', plots, '_UTM.txt', sep='')
treeFile <- paste0(path, 'trees/', plots, '_active.txt', sep='')

for(i in 1:length(genera)){
  
  genusName <- genera[i]
  
  seedData <- xytrap <- numeric(0)
  plotAll <- seedNames <- character(0)
  
  treeData <- xytree <- numeric(0)
  seedcols <- numeric(0)
  seedData <- character(0)
  
  for(j in 1:length(plots)){
    
    tfile <- treeFile[grep(plots[j],treeFile)]
    sfile <- seedFile[grep(plots[j],seedFile)]
    lfile <- locFile[grep(plots[j],locFile)]
    
    tmp    <- .treeFormat( tfile, genusName = genusName, changeNames = changeNames,
                           plot = plots[j], 
                           years = years, yrCols = yrCols  )
    yrDat  <- tmp$yrDat
    xyt    <- tmp$xytree
    if(length(yrDat) == 0)next
    
    
    if(user =="chase"){
       tmp <- .seedFormat(sfile, lfile, trapFile = '/Volumes/clark/clark.unix/makeMast/datafiles/seedTrapArea.txt',
                       genusName = genusName, omitNames = omitNames,
                       plot = plots[j], trapID = trapID )
      }else{
        tmp <- .seedFormat(sfile, lfile, trapFile = '../datafiles/seedTrapArea.txt',
                       genusName = genusName, omitNames = omitNames,
                       plot = plots[j], trapID = trapID )
    }
    
    
    if(length(tmp) == 0)next
    
    seedNames <- sort(unique(c(seedNames, tmp$seedNames)))
    xyseed   <- tmp$xy
    #  if(length(xytrap) > 0)xyseed   <- tmp$xy[,colnames(xytrap)]
    xytrap   <- rbind( xytrap, xyseed[,trapCols] ) 
    
    seedj  <- tmp$counts
    wcol <- sapply(seedj, is.numeric)
    counts <- as.matrix( tmp$counts[,which(wcol), drop=F] )
    
    
    seedData <- .appendMatrix(seedData, counts, fill=0)
    seedcols <- rbind(seedcols, seedj[,which(!wcol)])
    
    yrDat <- yrDat[yrDat$year %in% seedj$year,]
    xyt   <- xyt[xyt$treeID %in% yrDat$treeID,]
    
    treeData <- rbind(treeData, yrDat)
    xytree   <- rbind(xytree, xyt)
    
  }
  
  plotj <- plots[plots %in% seedcols[,'plot']]
  
  ws <- which( colSums(seedData[,seedNames, drop=F]) == 0 )
  if(length(ws) > 0){
    seedData <- seedData[,!colnames(seedData) %in% names(ws), drop=F]
    seedNames <- seedNames[!seedNames %in% names(ws)]
  }
  
  seedData <- data.frame(seedcols, seedData)
  specNames <- attr( treeData$species, 'levels')
  
  treeData <- treeData[treeData$year %in% seedData$year,]
  seedData <- seedData[seedData$year %in% treeData$year,]
  xytree   <- xytree[xytree$treeID %in% treeData$treeID,]
  
  # reproduction prior, probit scale
  
  repMu <- (treeData$diam - 30)/sd( treeData$diam, na.rm=T )
  repSd <- sqrt(1 + treeData$diam*( max( treeData$diam, na.rm=T ) - treeData$diam ) ) 
  
  treeData$repr[treeData$diam < 8] <- 0
  treeData$repr[treeData$diam > 30 & treeData$canopy > 0] <- 1
  treeData$repr[treeData$diam > 40] <- 1
  
  treeData$repMu <- signif(repMu, 3)
  treeData$repSd <- signif(repSd, 3)
  
  treeData$canopy <- jitter(treeData$canopy)
  
  #M <- .getM(specNames, seedNames, unknown = 'UNKN', unFraction = .9)
  
  treeData <- treeData[,c("plot","treeID","tree","species","year","region",
                          "repr","diam","canopy","growth")]
  seedData <- seedData[,c("plot","trapID","trap","year","active","area",seedNames)]
  
  xytree <- xytree[,c('tree','treeID','plot','x','y','UTMx','UTMy','elev')]
  xytrap <- xytrap[,c('trap','trapID','plot','x','y','UTMx','UTMy','elev')]
  
  wc <- which(colnames(xytree) %in% c('x','y','UTMx','UTMy'))
  colnames(xytree)[wc] <- c('xplot','yplot','x','y')
  colnames(xytrap)[wc] <- c('xplot','yplot','x','y')
  
  treeData[,c('diam','canopy','growth')] <- 
             round( treeData[,c('diam','canopy','growth')], 2 )
  
  if( user == "chase"){
    save(treeData, seedData, specNames, seedNames, 
       xytree, xytrap, plotj, years, # M, 
       file=paste('/Volumes/clark/clark.unix/makeMast/compressedFiles/clarkLab/', genFull[i],'.Rdata',sep='') )
  print(seedNames)
    
  } else{
    save(treeData, seedData, specNames, seedNames, 
       xytree, xytrap, plotj, years, # M, 
       file=paste('../compressedFiles/clarkLab/', genFull[i],'.Rdata',sep='') )
  print(seedNames)
  }
}
```

plot dimensions are here:

```{r fig.width=6, fig.height=6, fig.align='center'}

if(user == "chase"){
  path <- '/Volumes/clark/clark.unix/makeMast/compressedFiles'
  } else{
    path <- '../compressedFiles'
  }
folders <- list.files(path)

xynames <- c('x','y')

plotDims <- numeric(0)

genera   <- pnames <- character(0)
genFolds <- vector('list',length(folders))
names(genFolds) <- folders
allYears <- numeric(0)

for(m in 1:length(folders)){
  
  pk <- paste(path,folders[m],sep='/')
  lk <- list.files( pk )
  mk <- unlist(strsplit(lk,'.Rdata'))
  genFolds[[m]] <- mk
  genera <- c(genera, mk )
  
  rangexy <- numeric(0)
  
  for(j in 1:length(lk)){
    
    fj <- paste(pk,lk[j],sep='/')
    load(fj)
    
    xytree$plot <- as.factor(xytree$plot)
    
    pj <- levels(xytree$plot)
    pnames <- c(pnames,unique(pj))
    
    
    pf <- sort(unique(as.character(treeData$plot)))
 
      
    allYears <- unique( c(allYears, treeData$year, seedData$year) )
    
    if(length(rangexy) == 0){
      rangexy <- matrix( c(Inf, -Inf, Inf, -Inf), length(pf), 4, byrow=T)
      rownames(rangexy) <- pf
      colnames(rangexy) <- c('xmin','xmax','ymin','ymax')
    }else{
      wf <- which(!pf %in% rownames(rangexy))
      if(length(wf) > 0){
        nmat <- matrix(c(Inf, -Inf, Inf, -Inf), length(wf), 4, byrow=T)
        rownames(nmat) <- pf[wf]
        rangexy <- rbind(rangexy,nmat)
      }
    }
    
    for(k in 1:length(pf)){
      
      xy  <- xytree[as.character(xytree$plot) == pf[k],xynames]
      xy  <- rbind(xy, xytrap[as.character(xytrap$plot) == pf[k],xynames])
      rxy <- apply(xy,2,range,na.rm=T)
      
      if(rangexy[pf[k],1] > rxy[1,1])rangexy[pf[k],1] <- floor(rxy[1,1])
      if(rangexy[pf[k],2] < rxy[2,1])rangexy[pf[k],2] <- ceiling(rxy[2,1])
      if(rangexy[pf[k],3] > rxy[1,2])rangexy[pf[k],3] <- floor(rxy[1,2])
      if(rangexy[pf[k],4] < rxy[2,2])rangexy[pf[k],4] <- ceiling(rxy[2,2])
    }
    
  }
  
  px <- apply(rangexy[,1:2], 1, diff)
  py <- apply(rangexy[,3:4], 1, diff)
  area <- px*py/10000
  
  plotDims <- rbind(plotDims, cbind(rangexy,area) )
}


genera <- sort(unique(genera))
allPlots <- sort(unique(pnames))
allYears <- sort(unique(allYears))

gfolders <- vector('list',length(genera))
names(gfolders) <- genera
for(j in 1:length(genera)){
  
  gj <- character(0)
  for(k in 1:length(genFolds)){
    if(genera[j] %in% genFolds[[k]])gfolders[[j]] <- c(gfolders[[j]],names(genFolds)[k])
  }
}
```

traitTable for seed mass

```{r}
if(user =="chase"){
  priorVals  <- read.table('/Volumes/clark/clark.unix/makeMast/dataFiles/priorParameters.txt',header=T)
  traitTable <- read.table('/Volumes/clark/clark.unix/makeMast/vignettes/traitTable.txt',header=T)
  }else{
    priorVals  <- read.table('../dataFiles/priorParameters.txt',header=T)
    traitTable <- read.table('traitTable.txt',header=T)
}

```

DON'T RUN: Is there an output file?

```{r}
files <- paste(path,files,sep='/')
genera <- gsub("../compressedFiles/","",files)
genera <- gsub(".Rdata","",genera)

outPath <- '../../mastOutput/YR/'
outFiles <- list.files(outPath)

for(j in 1:length(genera)){
  
  for(k in 1:length(outFiles)){
    
    wjk <- grep(genera[j],outFiles[k])
    if(length(wjk) > 0){
      
      newf <- paste(outPath,outFiles[k],sep='')
      oldf <- grep(genera[j],files)
      files[oldf] <- newf
    }
  }
}
```

DON'T RUN: this block only if new plotArea, plotDims needed
```{r plotArea}          
  
dietzePlots <- c('B_C1P1', 'B_C1P2')
facePlots   <- paste('DF_FACE',c(1:6),sep='')
faceArea <- (pi*(30/2)^2)/10000
  
plotArea <- read.table("/nas/clark/clark.unix/allocationmodel/datafiles/treePlotAreaDuke.txt",
                       header=T)

pa <- as.matrix(plotArea[,-1])
rownames(pa) <- as.character(plotArea[,1])
plotArea <- pa
ww <- grep('FACE',rownames(plotArea))
if(length(ww) > 0)plotArea <- plotArea[-ww,]

darea <- matrix(plotDims[dietzePlots,'area'],length(dietzePlots), ncol(plotArea))
rownames(darea) <- dietzePlots

farea <- matrix(faceArea, 6, ncol(plotArea))
rownames(farea) <- facePlots

plotArea <- rbind(plotArea,darea,farea)
plotArea <- plotArea[allPlots,]

colnames(plotArea) <- .replaceString(colnames(plotArea),'X','')
plotArea <- plotArea[,as.character(allYears)]

myr <- c((max(allYears)+1):2026)

newcols <- matrix(NA,nrow(plotArea),ncol=length(myr))
newcols[,1:length(myr)] <- plotArea[,ncol(plotArea)]
colnames(newcols) <- myr
plotArea <- cbind(plotArea,newcols)
write.table( round(plotArea, 3), file='../plotArea.txt', quote=F)
write.table(plotDims, file='../plotDims.txt', quote=F)

```
    
  
Build combined files and build plotArea

```{r fit}
#skip <- c('acer')
badSeed <- c('fraxCaro')
notUsed <- c('IMMA')

notUsed <- NULL

tcols <- c('plot','tree','species','year','repr','diam')
scols <- c('plot','trap','year','area')
xy1n  <- c('plot','tree','x','y')
xy2n  <- c('plot','trap','x','y')

skip <- 'acer'

for(j in 1:length(genera)){
  
  if(genera[j] %in% skip)next
  
  genus <- genera[j]
  
  print(genus)
  
  tdata <- sdata <- xy1 <- xy2 <- numeric(0)
  seed <- spec <- character(0)
  nf <- length(gfolders[[j]])
  
  if(user == "chase"){
    plotDims <- read.table('/Volumes/clark/clark.unix/makeMast/plotDims.txt', header=T)
    plotArea <- read.table('/Volumes/clark/clark.unix/makeMast/plotArea.txt', header=T)
    }else{
      plotDims <- read.table('../plotDims.txt', header=T)
      plotArea <- read.table('../plotArea.txt', header=T)
      }
  
  colnames(plotArea) <- .replaceString(colnames(plotArea),'X','')
  
  for(k in 1:nf){
    
    pt <- paste(path,'/',gfolders[[j]][k],'/',genus,'.Rdata',sep='')
    load(pt)
    
    # only controls
    if(gfolders[[j]][k] == 'FACE'){
      treeData <- treeData[treeData$trt == 0 & treeData$nfert == 0,]
    }
    
    treeData$diam[treeData$diam == 0] <- NA
    
    treeID <- columnPaste(treeData$plot,treeData$tree)
    
    # interpolate missing diameters
    ii <- as.character(treeID)
    jj <- treeData$year
    jtimes <- sort(unique(jj))
    i  <- unique(ii)
    
    icol <- match(ii,i)
    jcol <- match(jj,jtimes)
    ijFull <- matrix(0,length(i),length(jtimes))
    ijFull[ cbind(icol,jcol) ] <- treeData$diam
    
    
    jmat <- .interpRows(ijFull, INCREASING=T, minVal=0, maxVal=300,
                            defaultValue=NULL, tinySlope=.00001) 
    wf <- which(is.finite(ijFull))
    jmat[wf] <- ijFull[wf]
    jmat <- round(jmat,2)
    
    treeData$diam <- jmat[ cbind(icol,jcol) ]
    
    tt    <- treeData[,tcols]
    tt$plot <- as.factor(tt$plot)
    tt$tree <- as.factor(tt$tree)
    
    tt$species <-  gen4code(tt$species, nn=4)
    
    if('fecMin' %in% colnames(treeData) & !'fecMin' %in% colnames(tdata)){
      tdata$fecMin <- rep(NA,nrow(tdata))
      tt$fecMin <- treeData$fecMin
    }
    if('fecMax' %in% colnames(treeData) & !'fecMax' %in% colnames(tdata)){
      tdata$fecMax <- rep(NA,nrow(tdata))
      tt$fecMax <- treeData$fecMax
    }
    
    if('fecMin' %in% colnames(tdata) & !'fecMin' %in% colnames(treeData)){
      treeData$fecMin <- rep(NA,nrow(treeData))
      tt$fecMin <- treeData$fecMin
    }
    if('fecMax' %in% colnames(tdata) & !'fecMax' %in% colnames(treeData)){
      treeData$fecMax <- rep(NA,nrow(treeData))
      tt$fecMax <- treeData$fecMax
    }
      
    tdata <- rbind(tdata,tt)
       
    ss    <- seedData[,scols]
    ss$plot <- as.factor(ss$plot)
    ss$trap <- as.factor(ss$trap)
    
 #   seedc <- grep(genus,colnames(seedData))
 #   if(length(seedc) == 0){
      gg <- substr(genus,1,4)
      seedc <- grep(gg,colnames(seedData))
 #   }else{
 #     gen <- gen4code(colnames(seedData)[seedc])
 #     colnames(seedData)[seedc] <- gen
 #   }
    seed <- c(seed,colnames(seedData)[seedc])
    spec <- c(spec,unique(as.character(tdata$species)))
    mm <- seedData[,seedc,drop=F]
    ss <- cbind(ss,mm)
    
    ww <- which(!colnames(sdata) %in% colnames(ss))
    if(length(ww) > 0){
      snew <- matrix(0,nrow(ss),length(ww))
      colnames(snew) <- colnames(sdata)[ww]
      ss <- cbind(ss,snew)[,colnames(sdata)]
    }
    
    sdata <- rbind(sdata,ss)
    
    xy1 <- rbind(xy1,xytree[,xy1n])
    xy2 <- rbind(xy2,xytrap[,xy2n])
  }
  treeData <- tdata
  seedData <- sdata
  xytree   <- xy1
  xytrap   <- xy2
  seedNames <- sort(unique(seed))
  specNames <- sort(unique(spec))
  
  seedNames <- seedNames[!seedNames %in% badSeed]
  for(m in 1:length(badSeed)){
    if( badSeed[m] %in% colnames(seedData) ){
      wun <- grep('UNKN',colnames(seedData))
      if(length(wun) > 0){
        seedData[,wun] <- seedData[,wun] + seedData[,badSeed[m]]
        seedData <- seedData[names(seedData) != badSeed[m]]
      }else{
        colnames(seedData)[colnames(seedData) == badSeed[m]] <- paste(genus,'UNKN',sep='')
      }
    }
  }
  
  spec <- as.character(treeData$species)
  
  if(genus == 'quercus'){
    wun  <- grep('UNKN',spec)
    spec[wun] <- 'querRubr'
    treeData$species <- as.factor(spec)
  }
  
  wun <- grep('UNKN',specNames)
  if(length(wun) > 0)specNames <- specNames[-wun]
  
  plots <- sort(unique(as.character(treeData$plot)))
  years <- sort(unique(c(treeData$year,seedData$year)))
  
  yr <- as.numeric(colnames(plotArea))
  kc <- as.character( yr[yr >= min(years)] )
  
  plotArea <- plotArea[plots,kc]
  plotDims <- plotDims[plots,]
  
  
  ##################### save combined data
  if(user =="chase"){
    cfile <- paste('/Volumes/clark/clark.unix/makeMast/combinedSites/',genus,'.Rdata',sep='')
  }else{
    cfile <- paste('../combinedSites/',genus,'.Rdata',sep='')
  }
  
  
  save( treeData, seedData, xytree, xytrap, seedNames, specNames,
        plotArea, plotDims, plotj, file=cfile) #added plot j 05/15/2018
  #########################
  
}
```

```{r}
#combine above data with GEE covariates

#pulling flowering timing information
#pulling google earth engine (GEE) covariate datasets

  if(user =="chase"){
    flowering <- read.csv("/Volumes/clark/clark.unix/makeMast/dataFiles/updated.spp.2018.csv")
    priorVals  <- read.table('/Volumes/clark/clark.unix/makeMast/dataFiles/priorParameters.txt',header=T)
    terr.data <- read.csv("/Volumes/clark/clark.unix/makeMast/dataFiles/all_mast.csv")
    pet.data <- read.csv("/Volumes/clark/clark.unix/makeMast/dataFiles/eto_mast.csv")
    pr.data <- read.csv("/Volumes/clark/clark.unix/makeMast/dataFiles/pr_mast.csv")
    tmax.data <- read.csv("/Volumes/clark/clark.unix/makeMast/dataFiles/tmax_mast.csv")
    tmin.data <- read.csv("/Volumes/clark/clark.unix/makeMast/dataFiles/tmin_mast.csv")
  }else{
    flowering <- read.csv('../dataFiles/updated.spp.2018.csv')
    priorVals <- read.table('../dataFiles/priorParameters.txt',header=T)
    terr.data <- read.csv("../dataFiles/all_mast.csv")
    pet.data <- read.csv("../dataFiles/eto_mast.csv")
    pr.data <- read.csv("../dataFiles/pr_mast.csv")
    tmax.data <- read.csv("../dataFiles/tmax_mast.csv")
    tmin.data <- read.csv("../dataFiles/tmin_mast.csv")
  }

all.covs <- list()

#matching GEE data and treedata by GEEID
tmp.data <- pet.data[,2:ncol(pet.data)] #CHECK TO SEE IF THIS IS THE SAME FOR ALL COVARIATE DATASETS. it should be
geeIDVector <- pet.data[,1]

yrID<- substr(colnames(tmp.data), 4,7)
uniqueYears<- unique(yrID)
moID<- substr(colnames(tmp.data), nchar(colnames(tmp.data)), nchar(colnames(tmp.data))) 
              
              yrMat<- matrix(yrID, nrow=nrow(tmp.data), ncol=ncol(tmp.data),byrow=T)
              moMat<- matrix(moID, nrow=nrow(tmp.data), ncol=ncol(tmp.data),byrow=T)
              geeIDMat<- matrix(geeIDVector, nrow=nrow(tmp.data), ncol=ncol(tmp.data),byrow=F) ### geeIDVector is just the column removed from the petMat
              
              yrMat[1:2,1:2] # should say 1, 1
             # 1, 1
              
              moMat[1:2,1:2]  # should say 1, 2
              #1, 2
              
              geeIDMat[1:2,1:2]  # should say 1, 1
              #2, 2
              
              #climatic water availability index, P - PET
              yearlyPETO <- aggregate(as.numeric(as.vector(as.matrix(pr.data[,-1] - pet.data[,-1]))), by=list(geeID=as.vector(geeIDMat), year=as.vector(yrMat)), sum) #sum instead of mean bc we want year end water balance to campare accross years, not average monthly
              yearlyPETO$IDyear <- IDyear <- paste0(yearlyPETO$geeID,'_', yearlyPETO$year)
              colnames(yearlyPETO) <- c("geeID","year","mean.annual.PETO","IDyear")
              
              #tmin 
              yearlytmin <- aggregate(as.numeric(as.vector(as.matrix(tmin.data[,-1]))), by=list(geeID=as.vector(geeIDMat), year=as.vector(yrMat)), mean)
              yearlytmin$IDyear <- IDyear <- paste0(yearlytmin$geeID,'_', yearlytmin$year)
              colnames(yearlytmin) <- c("geeID","year","mean.annual.tmin","IDyear")
              
              #tmax
              yearlytmax <- aggregate(as.numeric(as.vector(as.matrix(tmax.data[,-1]))), by=list(geeID=as.vector(geeIDMat), year=as.vector(yrMat)), mean)
              yearlytmax$IDyear <- IDyear <- paste0(yearlytmax$geeID,'_', yearlytmax$year)
              colnames(yearlytmax) <- c("geeID","year","mean.annual.tmax","IDyear")
              
              # adding all toeather with terr.data
              test <- merge(yearlyPETO, yearlytmin, by = "IDyear")
              test2 <- merge(test, yearlytmax, by = "IDyear")
              test3 <- merge(terr.data, test2, by = "geeID")
              drops <- c("geeID.x","year.x","geeID.y","year.y")
all.covs[[1]] <- merged.covs <- test3[ , !(names(test3) %in% drops)] #merged.covs are all the annual mean covaraites for every tree
names(all.covs)[[1]] <- "merged.covs"        

#now making species specific covariates based on seed set time and flowering time. This is going to be a beast
  #first going to tackle seed set time, floweing time should be more or less identical, and will appear after this section
              
              #for each data set i
              data.sets <- c("pet.data","pr.data","tmax.data","tmin.data")
              annual.data.sets <- c("yearlyPETO","yearlytmin","yearlytmax")
              
              #and each species within that data set j
              spp.names <- c('abies','acer','ailanthus','amelanchier','betula','carpinus',
                             'carya','celtis','cercis','chionanthus','cornus','fagus','fraxinus',
                             'ilex','juniperus','liquidambar','liriodendron','magnolia',
                             'morus','nyssa','ostrya','oxydendron','picea','pinus','prunus',
                             'quercus','robinia','sassafras','sorbus','tilia','tsuga','ulmus')
              data.abbrs <- c("eto","pr", "tmax", "tmin")
              data.years <- c(1979:2017)
              merged.covs.w.lag <- merged.covs
              
              #lag annual covs
              lag.annual.covs <- list()
              for(j in 1:length(spp.names)){
    
                  if(user =="chase"){
                  load(paste0('/Volumes/clark/clark.unix/makeMast/combinedSites/',spp.names[j],'.Rdata'))
                  }else{
                  load(paste0('../combinedSites/',spp.names[j],'.Rdata'))
                  }
                treeData$geeID <- paste0(treeData$plot,"_",treeData$tree)
                treeData$IDyear <- paste0(treeData$geeID,"_",treeData$year)
                
                #add lag covaraites
                #P-ET0
                mm<-match(paste0(treeData$IDyear), IDyear)
                mm.minus1<- match(paste0(treeData$geeID, '_', treeData$year-1), IDyear)
                mm.minus2<- match(paste0(treeData$geeID, '_', treeData$year-2), IDyear)
                sp.lag.covs <- as.data.frame(matrix(NA, nrow = nrow(treeData), ncol = length(annual.data.sets)*3+1))
                sp.lag.covs[,1] <- treeData$IDyear
                colnames(sp.lag.covs) <- c("IDyear", "yearlyPETO.t", "yearlyPETO.tmin1", "yearlyPETO.tmin2","yearlytmin.t", "yearlytmin.tmin1", "yearlytmin.tmin2","yearlytmax.t","yearlytmax.tmin1","yearlytmax.tmin2")
                l <- 2
                k <- 4
                for(p in 1:length(annual.data.sets)){
                  defDesign<- matrix(NA, nrow=nrow(treeData), ncol=3)
                  cov.data.iq <- get(annual.data.sets[p])
                  cov.data.col.iq <- cov.data.iq[,3]
                  defDesign[,1]<- cov.data.col.iq[mm]
                  defDesign[,2]<- cov.data.col.iq[mm.minus1]
                  defDesign[,3]<- cov.data.col.iq[mm.minus2]
                  
                  colnames(defDesign)<- c(paste0(annual.data.sets[p],".t"), paste0(annual.data.sets[p],".tmin1"), paste0(annual.data.sets[p],".tmin2")) # add species specific predictors depending on flowering times/seed set times.
                  #treeData<- as.data.frame(cbind(treeData$IDyear, defDesign))
                  #colnames(treeData)[1] <- "IDyear"
                  sp.lag.covs[,l:k] <- defDesign
                  l <- l+3
                  k <- k+3
                }
                lag.annual.covs[[j]] <- sp.lag.covs
              }
lag.covs <- lag.annual.covs
names(lag.covs) <- spp.names
all.covs[[2]] <- lag.covs
names(all.covs)[[2]] <- "lag.covs" #works up to here
              
              #open a species spefic treeData file from ClarkLab
              spp.specific.annual.mean.cov.vals <- list()
              for(j in 1:length(spp.names)){
                
                if(user =="chase"){
                  load(paste0('/Volumes/clark/clark.unix/makeMast/combinedSites/',spp.names[j],'.Rdata'))
                  }else{
                  load(paste0('../combinedSites/',spp.names[j],'.Rdata'))
                  }
                
                treeData$geeID <- paste0(treeData$plot,"_",treeData$tree)
                treeData$IDyear <- paste0(treeData$geeID,"_",treeData$year)
                this.spp.cov<- list()
                #create a vector with the geeID of 
                  for(i in 1:length(data.sets)){
                    
                    data.iq <- as.data.frame(get(paste0(data.sets[i])))
                    
                #subset the rows of dataset i by all individuals of species j that are within dataset i
                    reduced.data <- subset(data.iq, data.iq[,1] %in% treeData$geeID)
                
                #average values from dataset i for species j's flowering season
                    treeData$f.start <- flowering$f.start[ match(treeData$species, flowering$long.code)]
                    treeData$f.end <- flowering$f.end[ match(treeData$species, flowering$long.code)]
                    f.series <- treeData[1, "f.start"] :  treeData[1, "f.end"] #flowering time
                    
                #average values from dataset i for species j's seed setting season
                    treeData$d.start <- flowering$d.start[ match(treeData$species, flowering$long.code)]
                    s.series <- treeData[1, "f.end"] :  treeData[1, "d.start"] #seed set season defoined by end of flowering to the start of dispersal. This could be changed with more theory. 
                    
                #creating a vector of column names to pull from dataset i
                    a <- data.abbrs[i]
                    names.vec <- NULL
                    counter <- 1
                    
                      for(k in 1:length(data.years)){
                      b <- data.years[k]
                        for(m in 1:length(s.series)){
                          c <- s.series[m]
                            if (c <= 9){
                              c <- paste0("0",c)
                            } else{
                              c <- paste0(c)
                            }
                          col.tmp <- paste0(a,b,"_",c)
                          names.vec[counter] <- col.tmp
                          counter <- counter+1
                        }
                      }
                    
                  #further reducing data to columns that match this species seed set times
                    more.reduced.data <- reduced.data[,names.vec]
                    mean.reduced.data <- matrix(NA, nrow = nrow(more.reduced.data), ncol = length(data.years), dimnames = list(reduced.data$geeID, data.years))
                    cols.iq <- 1:length(s.series)
                    
                        for(n in 1:nrow(mean.reduced.data)){
                            for(g in 1:length(data.years)){
                              #if cols iq <= 1 then take the value, if >1, take mean
                              if (length(s.series) < 2){
                                mean.reduced.data[n,g] <- more.reduced.data[n,cols.iq]
                              } else{
                                mean.reduced.data[n,g] <- rowMeans(more.reduced.data[n,cols.iq])
                              }
                                cols.iq <- cols.iq + length(s.series)
                            }
                          cols.iq <- 1:length(s.series)
                        }
                    mean.reduced.data <- as.data.frame(mean.reduced.data)
                    mean.reduced.data$IDyear <- rownames(mean.reduced.data)
                    this.spp.cov[[i]] <- mean.reduced.data
                  }
                names(this.spp.cov) <- data.sets
                spp.specific.annual.mean.cov.vals[[j]] <- this.spp.cov
              }
seed.set.covs <- spp.specific.annual.mean.cov.vals
names(seed.set.covs) <- spp.names
all.covs[[3]] <- seed.set.covs
names(all.covs)[[3]] <- "seed.set.covs"
save(all.covs, file = "~/Desktop/allcovs.rdata")
                    
  #now for flowering time         
    #open a species spefic treeData file from ClarkLab
    spp.specific.annual.mean.cov.vals <- list()
    for(j in 1:length(spp.names)){
      
        if(user =="chase"){
        load(paste0('/Volumes/clark/clark.unix/makeMast/combinedSites/',spp.names[j],'.Rdata'))
        }else{
        load(paste0('../combinedSites/',spp.names[j],'.Rdata'))
        }
      
      treeData$geeID <- paste0(treeData$plot,"_",treeData$tree)
      treeData$IDyear <- paste0(treeData$geeID,"_",treeData$year)
      
      #create a vector with the geeID of 
      f.this.spp.cov <- list()
      for(i in 1:length(data.sets)){
        data.iq <- as.data.frame(get(paste0(data.sets[i])))
        #subset the rows of dataset i by all individuals of species j that are within dataset i
        reduced.data <- subset(data.iq, data.iq[,1] %in% treeData$geeID)
        
        #average values from dataset i for species j's flowering season
        treeData$f.start <- flowering$f.start[ match(treeData$species, flowering$long.code)]
        treeData$f.end <- flowering$f.end[ match(treeData$species, flowering$long.code)]
        f.series <- treeData[1, "f.start"] :  treeData[1, "f.end"] #flowering time
        
        #creating a vector of column names to pull from dataset i
        a <- data.abbrs[i]
        names.vec <- NULL
        counter <- 1
        
        for(k in 1:length(data.years)){
          b <- data.years[k]
          for(m in 1:length(f.series)){
            c <- f.series[m]
            if (c <= 9){
              c <- paste0("0",c)
            } else{
              c <- paste0(c)
            }
            col.tmp <- paste0(a,b,"_",c)
            names.vec[counter] <- col.tmp
            counter <- counter+1
          }
        }
        
        #further reducing data to columns that match this species seed set times
        more.reduced.data <- reduced.data[,names.vec]
        mean.reduced.data <- matrix(NA, nrow = nrow(more.reduced.data), ncol = length(data.years), dimnames = list(reduced.data$geeID, data.years))
        cols.iq <- 1:length(f.series)
        
        for(n in 1:nrow(mean.reduced.data)){
          for(g in 1:length(data.years)){
            #if cols iq <= 1 then take the value, if >1, take mean
            if (length(f.series) < 2){
              mean.reduced.data[n,g] <- more.reduced.data[n,cols.iq]
            } else{
              mean.reduced.data[n,g] <- rowMeans(more.reduced.data[n,cols.iq])
            }
            cols.iq <- cols.iq + length(f.series)
          }
          cols.iq <- 1:length(f.series)
        }
        mean.reduced.data <- as.data.frame(mean.reduced.data)
        mean.reduced.data$IDyear <- rownames(mean.reduced.data)
        f.this.spp.cov[[i]] <- mean.reduced.data
      }
      names(f.this.spp.cov) <- data.sets
      spp.specific.annual.mean.cov.vals[[j]] <- f.this.spp.cov
      
    }
    
flowering.covs <- spp.specific.annual.mean.cov.vals    
names(flowering.covs) <- spp.names
all.covs[[4]] <- flowering.covs
names(all.covs)[[4]] <- "flowering.covs"

save(all.covs, file = "~/Desktop/all.covs.rdata")
    
all.cov.names <- c("merged.covs","lag.covs","seed.set.covs","flowering.covs")

#now combining covariates with all species tree data, making them ready to import into MASTIF
library(tidyr)
layer.names <- c("pet.data",  "pr.data",   "tmax.data", "tmin.data")
all.treeData <- list()
for(t in 1:length(spp.names)){
  
  if(user =="chase"){
  load(paste0('/Volumes/clark/clark.unix/makeMast/combinedSites/',spp.names[t],'.Rdata'))
  }else{
  load(paste0('../combinedSites/',spp.names[t],'.Rdata'))
  }
  
  treeData$IDyear <- paste0(treeData$plot, "_", treeData$tree, "_", treeData$year)
  for(c in 1: length(all.cov.names)){
    data.layer.iq <- all.covs[[c]]
    if (c > 1){
      if (c < 3){ #for layer 2
        spp.iq <- data.layer.iq[[t]]
        new <- merge(treeData,spp.iq, by="IDyear", all.x=TRUE)
      } else{ #for problem layers 3 and 4
        spp.iq <- data.layer.iq[[t]]
        
        for(gg in 1: length(spp.iq)){ #pulling out each cov layer for this spp
          spp.cov.iq <- spp.iq[[gg]]
          spp.cov.iq$IDyear <- factor(spp.cov.iq$IDyear)
          spp.cov.iq.long <- gather(spp.cov.iq, year, variable, "1979":"2017", factor_key=TRUE)
          colnames(spp.cov.iq.long)[3] <- paste0(all.cov.names[c], "_", names(spp.iq[gg]))
          spp.cov.iq.long$IDyear <- paste0(spp.cov.iq.long$IDyear,"_",spp.cov.iq.long$year)
          if (gg < 2){
            spp.all.cov.holder <- NULL
            spp.all.cov.holder <- rbind(spp.all.cov.holder,spp.cov.iq.long)
          } else{
            spp.all.cov.holder <- merge(spp.all.cov.holder,spp.cov.iq.long[,c(1,3)], by="IDyear", all.x=TRUE)
          }
        }
        new <-  merge(treeData,spp.all.cov.holder , by="IDyear", all.x=TRUE)
      }
      new$year.x <- new$year.y <-  NULL
      treeData <- new
      #need to save new treeData in another matrix?
    } else{
      new <- merge(treeData, data.layer.iq, by="IDyear", all.x=TRUE)
    treeData <- new
    }
    all.treeData[[t]] <- new
  }
} 
names(all.treeData) <- spp.names

#adding "year" back in
for( i in 1: length(all.treeData)){
  all.treeData[[i]]$year <- sub('.*\\_', '', all.treeData[[i]]$IDyear)
}

  if(user =="chase"){
  save(all.treeData, file ='/Volumes/clark/clark.unix/makeMast/combinedSites/all.treeData.rdata')
  }else{
  save(all.treeData, file = '../combinedSites/all.treeData.rdata')
  }
```

```{r}
#creating a seperate file holding all non-cov infor for each species instead of adding another list to the monstrosity above
spp.names <- c('abies','acer','ailanthus','amelanchier','betula','carpinus',
               'carya','celtis','cercis','chionanthus','cornus','fagus','fraxinus',
               'ilex','juniperus','liquidambar','liriodendron','magnolia',
               'morus','nyssa','ostrya','oxydendron','picea','pinus','prunus',
               'quercus','robinia','sassafras','sorbus','tilia','tsuga','ulmus')
data.names <- c("seedData", "xytrap", "xytree", "plotj", "seedNames", "specNames", "years")
otherTreeData <- list()
for(ss in 1:length(spp.names)){
  
  if(user =="chase"){
  load(paste0('/Volumes/clark/clark.unix/makeMast/combinedSites/',spp.names[ss],'.Rdata'))
  }else{
  load(paste0('../combinedSites/',spp.names[ss],'.Rdata'))
  }
 
  tmp.holder <- list()
    for(qq in 1: length(data.names)){
      tmp.holder[[qq]] <- get(paste0(data.names[qq]))
    }
  names(tmp.holder) <- data.names
 otherTreeData[[ss]] <- tmp.holder
}

names(otherTreeData) <- spp.names

  if(user =="chase"){
  save(otherTreeData, file ='/Volumes/clark/clark.unix/makeMast/combinedSites/otherTreeData.rdata')
  }else{
  save(otherTreeData, file = '../combinedSites/otherTreeData.rdata')
  }
```


```{r, echo=F}
#ANALYSIS STARTS HERE
rm(list=ls())
remove.packages("mastif", "/Library/Frameworks/R.framework/Versions/3.3/Resources/library")
install.packages("~/Documents/GitHub/mast/mastif_1.0.tar.gz", repos = NULL, type = "source") #upload the most recent package from gitHub
library(mastif)
library(Rcpp)
library(RANN)
library(corrplot)
library(stringr)

username <- function() 
{ 
readline("Please enter username:  ")
} 
user <- username()
print(paste0("proceeding as ", user))
```

```{r, echo=F}
if(user =="chase"){
  load("/Volumes/clark/clark.unix/makeMast/combinedSites/all.treeData.rdata")
  load("/Volumes/clark/clark.unix/makeMast/combinedSites/otherTreeData.rdata")
  traitTable <- read.table('/Volumes/clark/clark.unix/traitTable.txt',header=T)
  priorVals  <- read.table("/Volumes/clark/clark.unix/makeMast/dataFiles/priorParameters.txt", header = TRUE)
}else{
  # jim's laptop
  cpath <- "/Volumes/research/clark/clark.unix/makeMast/"
  load( paste(cpath,'combinedSites/all.treeData.rdata',sep='') )
  load( paste(cpath,'combinedSites/otherTreeData.rdata',sep=''))
  traitTable <- read.table( paste(cpath,'vignettes/traitTable.txt',sep=''),
                            header=T)
  priorVals  <- read.table(paste(cpath,'dataFiles/priorParameters.txt',sep=''),
                           header = TRUE)
}

genera <- c('abie','acer','aila','amel','betu','carp',
            'cary','celt','cerc','chio','corn','fagu','frax',
            'ilex','juni','liqu','liri','magn',
            'moru','nyss','ostr','oxyd','pice','pinu','prun',
            'quer','robi','sass','sorb','tili','tsug','ulmu')

genFull <- c('abies','acer','ailanthus','amelanchier','betula','carpinus',
             'carya','celtis','cercis','chionanthus','cornus','fagus','fraxinus',
             'ilex','juniperus','liquidambar','liriodendron','magnolia',
             'morus','nyssa','ostrya','oxydendron','picea','pinus','prunus',
             'quercus','robinia','sassafras','sorbus','tilia','tsuga','ulmus')

omitNames   <- c('acerIMMA','liriTuli_flower','betuUNKN_flower','caryIMMA',
                 'cornIMMA','acerRubr_flower',' betuUNKN_flower',
                 'nyssIMMA','oxydArbo_flower','oxydIMMA','pinuImma_fruit',
                 'piceRubeIMMA','querIMMA','tiliAmer_flower')

changeNames <- rbind( cbind('ulmuUNKN','ulmuAlat'),
                      cbind('acerUNKN','acerRubr'),
                      cbind('acerrubr','acerRubr'))

output.folder.name <- "output.05.26.18/"
setwd("/Volumes/research/clark/clark.unix/makeMast/vignettes")

if(user =="chase"){
  dir.create(paste0('/Volumes/clark/clark.unix/makeMast/comboAnalysis/',output.folder.name))
  }else{
  dir.create(paste0('../comboAnalysis/',output.folder.name))
  }

#spp in loop status/errors
#need to re-run with new MASTIF package

#1 OK
#2 OK
#3 OK
#4 OK
#5 OK
#6 OK
#7 OK
#8 Error in plotDims[, "area"] : incorrect number of dimensions
#9 OK
#10 all immature, not enough seeds
#11 OK
#12 OK
#13 OK
#14 [.data.frame`(sdata, , keepCol) : undefined columns selected
#15 OK
#16 OK
#17 OK
#18 OK
#19 OK
#20 OK
#21 OK
#22 OK
#23 OK
#24 OK
#25 OK
#26 OK
#27 OK
#28 not enough seeds
#29 Error in plotDims[, "area"] : incorrect number of dimensions
#30 OK
#31 OK
#32 OK

require(stringr)

for(t in 1:length(genFull)){
  covTreeData <- all.treeData[[t]]
  covTreeData$province <- sub('\\_.*', '', covTreeData$plot)
  covTreeData$province <- str_replace(covTreeData$province, "DF", "piedmont")
  covTreeData$province <- str_replace(covTreeData$province, "MH", "sApps")
  covTreeData$province <- str_replace(covTreeData$province, "CW", "sApps")
  covTreeData$province <- str_replace(covTreeData$province,"GSNP", "sApps")
  covTreeData$province <- str_replace(covTreeData$province, 'HF', 'NE')
  covTreeData$province <- str_replace(covTreeData$province, 'B', 'NE')
  
  names(covTreeData) <- gsub("_", ".", names(covTreeData))

  covTreeData$f.PETO <- (covTreeData$flowering.covs.pr.data - covTreeData$flowering.covs.pet.data)
  covTreeData$s.PETO <- (covTreeData$seed.set.covs.pr.data - covTreeData$seed.set.covs.pet.data)
  otherTreeData.now <- otherTreeData[[t]]
  
#  seedNames <- otherTreeData.now$seedNames
#  seedData  <- otherTreeData.now$seedData
  
#dealing with UNKN fruits
  wf <- grep('UNKN_fruit',otherTreeData.now$seedNames)
  if(length(wf) > 0){
    otherTreeData.now$seedNames[wf] <- 'unknfruit'
    wf <- grep('UNKN_fruit',colnames(otherTreeData.now$seedData))
    colnames(otherTreeData.now$seedData)[wf] <- 'unknfruit'
  }
  
  wf <- grep('UNKN', otherTreeData.now$seedNames)
  if(length(wf) > 1)stop('multiple unknowns')
  
  wspec <- match(otherTreeData.now$specNames,traitTable$code4)
  seedMass <- as.matrix( traitTable[wspec,'gmPerSeed',drop=F] )*1000
  rownames(seedMass) <- specNames
  
  wna <- which(is.na(seedMass))
  if(length(wna) > 0){
    seedMass[wna] <- mean(seedMass,na.rm=T)
  }
  
  print(seedMass)

#fixing col names to be compatible with MASTIF
 # names(covTreeData) <- str_replace_all(names(covTreeData), "[[.]]", "")
  
  if(user =="chase"){
    dir.create(paste0('/Volumes/clark/clark.unix/makeMast/comboAnalysis/',
                      output.file.name))
    setwd(paste0('/Volumes/clark/clark.unix/makeMast/comboAnalysis/',
                 output.file.name))
  }else{
    dir.create(paste0('../comboAnalysis',output.file.name))
    setwd(paste0('../comboAnalysis',output.file.name))
  }
  
  formulaFec <- as.formula( ~ I(log(diam)) + yearlyPETO.tmin1 + yearlyPETO.tmin2 + flowering.covs.pr.data + flowering.covs.tmin.data + s.PETO)

  formulaRep <- as.formula( ~ I(log(diam)) )
  
  randomEffect <- list(randGroups = 'treeID',
                       formulaRan = as.formula( ~ I(log(diam)) ) )
  yearEffect <- list(specGroups = 'species', plotGroups = 'province')
  
  priors <- priorVals[priorVals$genus == genFull[t],]
  plots <- sort(unique(as.character(otherTreeData.now$plot)))
  years <- sort(unique(c(otherTreeData.now$year,otherTreeData.now$seedData$year)))
  covTreeData$province <- as.factor(covTreeData$province)
  
  inputs   <- list( specNames = otherTreeData.now$specNames, 
                    seedNames = otherTreeData.now$seedNames, 
                    treeData = covTreeData, seedData = otherTreeData.now$seedData,
                    xytree = otherTreeData.now$xytree, xytrap = otherTreeData.now$xytrap, priorDist = priors$priorDist, 
                    priorVDist = priors$priorVDist, minDist = priors$minDist, 
                    maxDist = priors$maxDist, minDiam = priors$minDiam, 
                    maxDiam = priors$maxDiam, maxF = priors$maxF)
  predPlots <- plots
  predList <- list(mapMeters = 10, plots = predPlots, years = years )
  
  output <- mastif(formulaFec, formulaRep,  inputs = inputs, ng =200, 
                   burnin = 20, yearEffect = yearEffect,
                   randomEffect = randomEffect,predList = predList)
  
  if(user =="chase"){
    save(output, file = paste0('/Volumes/clark/clark.unix/makeMast/comboAnalysis/',
                               output.file.name, "/", genFull[t],"output.rdata"))
  }else{
    save(output, file = paste0('../comboAnalysis/',output.folder.name,
                               genFull[t],"output.rdata"))
  }
}
```
